//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterTwitter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterTwitter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterTwitter needs storage access so that you can save photos. Please enable it in Settings.
        /// </summary>
        internal static string AskForStoragePermission {
            get {
                return ResourceManager.GetString("AskForStoragePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type your email.
        /// </summary>
        internal static string BlankEmailError {
            get {
                return ResourceManager.GetString("BlankEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type your name.
        /// </summary>
        internal static string BlankNameError {
            get {
                return ResourceManager.GetString("BlankNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string BookmarksTitle {
            get {
                return ResourceManager.GetString("BookmarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change it in settings.
        /// </summary>
        internal static string ChangePermissionSettings {
            get {
                return ResourceManager.GetString("ChangePermissionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string CreateYourAccount {
            get {
                return ResourceManager.GetString("CreateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all bookmarks.
        /// </summary>
        internal static string DeleteAllBookmarks {
            get {
                return ResourceManager.GetString("DeleteAllBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all bookmarks?.
        /// </summary>
        internal static string DeleteAllBookmarksConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteAllBookmarksConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all bookmarks?.
        /// </summary>
        internal static string DeleteAllBookmarksConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteAllBookmarksConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string DoNotMatch {
            get {
                return ResourceManager.GetString("DoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email! It should contain @ and a domain..
        /// </summary>
        internal static string EmailInputError {
            get {
                return ResourceManager.GetString("EmailInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have empty fields! Please, fill them..
        /// </summary>
        internal static string EmptyFieldsError {
            get {
                return ResourceManager.GetString("EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your account.
        /// </summary>
        internal static string GetYourAccount {
            get {
                return ResourceManager.GetString("GetYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use at least 1 uppercase letter and 1 digit.
        /// </summary>
        internal static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In error!.
        /// </summary>
        internal static string LogInErrorTitle {
            get {
                return ResourceManager.GetString("LogInErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to logout?.
        /// </summary>
        internal static string LogoutAlertBody {
            get {
                return ResourceManager.GetString("LogoutAlertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LogoutAlertCancel {
            get {
                return ResourceManager.GetString("LogoutAlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string LogoutAlertOk {
            get {
                return ResourceManager.GetString("LogoutAlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutAlertTitle {
            get {
                return ResourceManager.GetString("LogoutAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should contain only latin characters!.
        /// </summary>
        internal static string NameInputError {
            get {
                return ResourceManager.GetString("NameInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There mustn&apos;t be whitespaces inside your name!.
        /// </summary>
        internal static string NameMustNotContainWhitespace {
            get {
                return ResourceManager.GetString("NameMustNotContainWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no any user with such email and password! Please, check your inputs once more or visit Sign Up page..
        /// </summary>
        internal static string NoSuchUser {
            get {
                return ResourceManager.GetString("NoSuchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password: use at least 6 symbols, 1 upper case and 1 digit..
        /// </summary>
        internal static string PasswordInputInvalid {
            get {
                return ResourceManager.GetString("PasswordInputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type at least 6 symbols.
        /// </summary>
        internal static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission was denied.
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write any text to your post.
        /// </summary>
        internal static string PostEmpty {
            get {
                return ResourceManager.GetString("PostEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile in blacklist.
        /// </summary>
        internal static string ProfileInBlacklist {
            get {
                return ResourceManager.GetString("ProfileInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from blacklist.
        /// </summary>
        internal static string RemoveFromBlacklist {
            get {
                return ResourceManager.GetString("RemoveFromBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission for saving is denied.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was saved to gallery.
        /// </summary>
        internal static string SaveSucces {
            get {
                return ResourceManager.GetString("SaveSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveTitle {
            get {
                return ResourceManager.GetString("SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inputs are not valid! Please, check them once more and try again!.
        /// </summary>
        internal static string SignUpErrorMessage {
            get {
                return ResourceManager.GetString("SignUpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up error!.
        /// </summary>
        internal static string SignUpErrorTitle {
            get {
                return ResourceManager.GetString("SignUpErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists!.
        /// </summary>
        internal static string SuchUserAlreadyExists {
            get {
                return ResourceManager.GetString("SuchUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        internal static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no bookmarks yet.
        /// </summary>
        internal static string YouHaveNoBookmarksYet {
            get {
                return ResourceManager.GetString("YouHaveNoBookmarksYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll need a password.
        /// </summary>
        internal static string YouLlNeedAPassword {
            get {
                return ResourceManager.GetString("YouLlNeedAPassword", resourceCulture);
            }
        }
    }
}
